# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: 
        - 20.6
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - name: Checking out
        uses: actions/checkout@v3
        env:
          GIT_SSL_NO_VERIFY: true
        with:
          token: '${{ secrets.G_TOKEN }}'
      - name: 'Use Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v3
        with:
          node-version: '${{ matrix.node-version }}'
      - name: Install dependencies
        run: |
          npm install
  linter:
    name: Lint Test  
    runs-on: ubuntu-latest
    steps:
      - name: Checking out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.G_TOKEN }}
      - name: Debug Git Information
        run: |
          echo "Commit SHA: ${{ github.sha }}"
          echo "Repository URL: ${{ github.repository }}"
          git log -1
      - name: Run MegaLinter
        id: ml
        uses: oxsecurity/megalinter/flavors/javascript@beta
        env:
          ENABLE: JAVASCRIPT_ES
          GITHUB_TOKEN: '${{ secrets.G_TOKEN }}'
      - name: Archive production artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: MegaLinter reports
          path: |
            megalinter-reports
            mega-linter.log    
   
  semgrep:
    name: Semgrep Scan
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
      - name: Install node
        run: apk add --no-cache nodejs
      - name: Checking out
        uses: actions/checkout@v4
      - name: Semgrep Scan
        run: semgrep scan --sarif > semgrep.sarif
      - name: save logs
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: semgrep-report
          path: semgrep.sarif
          retention-days: 3
  build-push-image:
    needs:
      - build
      - linter
      - semgrep
    runs-on: ubuntu-latest
    steps:
      - name: Checking out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: docker login
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: '${{ secrets.DOCKER_USER }}'
          password: '${{ secrets.DOCKER_PASSWORD }}'
      - name: Setup docker build
        uses: docker/setup-buildx-action@v3
      - name: print
        run: echo ${{ github.sha }}
      - name: Build image and push to Docker Hub
        id: push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: 'yli2935/gitops01:${{ github.sha }}'
      - name: Image digest
        run: 'echo ${{ steps.docker_build.outputs.digest }}'  